### ISSUE TITLE
Is it Async-callback safe?

### ISSUE THREAD

**Issue by gadmm** [c-cube/thread-local-storage#2]
There are two questions related to async callbacks. This is an important use-case for me; using TLS from a memprof callback (in which case it can happen before you have the time to initialise the tls by hand) is very natural.
- Is it safe against racing with an async callback? (e.g. accessing the TLS from an async callback). Notice that the claim that compute is called only once per thread is not correct in case of such a race. Also, there is a risk that a race while extending the array might put the tls back to a previous state. This can be fixed by requiring that TLS is not accessed during async callbacks, or with a compare-and-set trick (see https://github.com/ocaml/ocaml/pull/12889) plus some statement about `compute` being possibly called several times.
- Is the TLS state protected against async exceptions? This seems to be the case here, thanks to the read-copy-update nature of the operations, except for one aspect: this can also break the rule that `compute` is called only once, if the exception happens during compute.

I might look (on my side) into a simpler implementation that is simple yet async-callback-safe, with:
- the key comes with a default value rather than an initialization function
- get performs no mutation/allocation and is allowed inside async callbacks
- set mutates/allocates and is not allowed in async callbacks

**Comment by gadmm** [comment]
I have created a fork taylored to my own uses here https://github.com/gadmm/thread-local-storage.

I will need to vendor it anyway so I am happy to maintain my own branch. However, let me know if I can assist in any way to fix the problems with the original package. Note that although I could open a PR to introduce my fixes, the API is incompatible, and I am not sure how much you are ready to change it.

**Comment by c-cube** [comment]
I see, it looks more like a (possibly empty) reference, a more classic API really. Is the performance on par (or better), and compatible with older versions of OCaml still? If so, I think it's reasonable to move to this new API if it makes it easier to handle async exceptions.

**Comment by gadmm** [comment]
I think one can keep the principle of an initialization function. There simply needs to be another method to read the TLS without causing side-effects together and accompanying documentation. I will probably send a proposal when I get round to it, let me know if you've got any thoughts.

Small problem I noticed: if I vendor such a lib and someone else depends on this package, then the two libs will compete for the same field of the thread descriptor. I also wonder what happens if several copies are loaded (e.g. using dynamic linking), in case there are issues there. For all of this, I think there is a lot of incentives to have a single reference package that the community agrees it "owns" this thread descriptor field. So I'm extra motivated to make it work for my use-case.

I also tried to think of alternatives:
- Decide that the first field should always contain the sentinel, and check during writes that the sentinel is correct, so as to fail early in case of corruption.
- Figure some kind of coordination between different packages which want to own the field such that it works.

Am I overthinking the issue? Any idea as to how this kind of issues is dealt with usually?

> Is the performance on par (or better), and compatible with older versions of OCaml still?

I have not made any benchmark, and in principle there is no impact on performance necessary. However, I made independent changes to improve the code generation, because the code generation from the OCaml compiler is abysmal compared to what you'd expect for a TLS read function. I ended-up writing a part of it as a noalloc C function for that reason.

I removed compatibility with OCaml < 4.12 because I plan on depending on memprof anyway.

**Comment by c-cube** [comment]
> For all of this, I think there is a lot of incentives to have a single reference package that the community agrees it "owns" this thread descriptor field. 

I agree, I'm also game to move this to ocaml-community or ocaml-multicore or wherever it can best be of service to the community. I think it's better to have as low level an API as possible in at least one module (direct get/set like you want) so that it's maximally flexible. I can add a build function if I want on top of that, it's really not important.

I think compat with < 4.12 is important in general, using dune conditionals or a preprocessor (ucppo?) if needed.
